server:
  port: 8888

logging:
  level:
    org.springframework.cloud: 'DEBUG'

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ExampleDriven/spring-cloud-config-example
          # The git repo will be cloned to this directory
          basedir: target/config
          # within the cloned git repo search for properties in this directory
          searchPaths: properties-git
        native:
          searchLocations: file:../properties-local

# Activate this using -Dspring.profiles.active=native
#  profiles:
#    active: native